language: node_js
node_js:
    - "10"

cache: npm

install:
    - npm install

script:
    - npm run build

deploy:
  provider: pages
  local_dir: dist
  name: solingjjes
  email: 1600346867@qq.com
  skip_cleanup: true
  # target_branch
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false #保持分支的commit历史，而不是git push --force覆盖gh_pages分支的更新的记录
  on:
    branch: master